### ISSUE TITLE
Measuring of quantum state of a many-body quantum system in computational basis

### ISSUE THREAD

**Issue by shadibeh** [jcmgray/quimb#103]
Hi every one.

I would like to measure a quantum state consisted of a large number of spins (around 300 spins) in computational basis. 
So, the simplest way to do that is to find all the spin configurations in computational basis and find the squared inner product of each possible configuration and the quantum state to find the probability.

However, it requires large memory and takes long time.
Would you please let me know if there is any approach in quimb to do it faster.
Thanks

**Comment by jcmgray** [comment]
Hi @shadibeh 

> However, it requires large memory and takes long time.

Yes 2^300 ~ 10^90 is a very large number!

You don't specify what representation you have of your quantum state? but assuming it is e.g. a tensor network representation, then one performs this generally by computing a series of conditioned marginal probability distributions and sampling from these in a chain. See for example the `quimb` docs here 
- https://quimb.readthedocs.io/en/latest/tensor-circuit.html#Compute-a-marginal-probability-distribution  and
- https://quimb.readthedocs.io/en/latest/tensor-circuit.html#Generate-unbiased-samples.
however, note this is only possible if the TN representation can be contracted (i.e. is 'close enough to a tree').

**Comment by shadibeh** [comment]
Thank you very much for the explanations.
The links were very helpful.

Thanks
