### ISSUE TITLE
Integrating quantum hardware systems with Quimb

### ISSUE THREAD

**Issue by DarthMalloc** [jcmgray/quimb#104]
Hi @jcmgray, Is it possible to integrate quantum hardware systems like IBM quantum with Quimb? I seem to recall reading somewhere about that.

**Comment by jcmgray** [comment]
I don't think so - on the software side it might be possible to use `quimb` as a classical backend for `qiskit` etc., but I'm not aware of any such interfaces yet.

**Comment by DarthMalloc** [comment]
Thanks for getting back to me about that. I was also wondering how the `circ_ansatz_1D_brickwork` model was conceived. Is there any literature on that particular class of tensor network?

**Comment by jcmgray** [comment]
I'm not sure if it was conceived anywhere in particular, but it its simply the densest tiling of gates you can do so a natural thing to study (e.g. https://arxiv.org/abs/2107.01307). It's also the same geometry generated by trotterizing a nearest neighbor hamiltonian into even and odd pairs.
