### ISSUE TITLE
Bug in high-spin TEBD calculation

### ISSUE THREAD

**Issue by TanTsiChen** [jcmgray/quimb#11]
Hi, Johnnie

`H = qtn.NNI_ham_XY(n=10, S=1)`
`psi0 = qtn.MPS_computational_state('0'*10)`
`tebd = qtn.TEBD(psi0, H)`
`tebd.updata_to(1, tol=1e-3)`
The code returns a ValueError, it's about the function 'gate_split' in 'tensor_1d.py', the size of gate has been set to `(2, 2, 2, 2)`, but when `spin = 1`, it should be `(3, 3, 3, 3)`, so it cannot reshape array of size 81 into shape `(2, 2, 2, 2)`. It's better to set the size to be `(spin*2+1, spin*2+1, spin*2+1, spin*2+1)`.

thanks,
Qicheng

**Comment by jcmgray** [comment]
This problem is not to do with the gate but rather because ``MPS_computational_state`` is for 'qubits' (i.e. spin-1/2). You could use 
```python
psi0 = qtn.MPS_product_state([[1., 0., 0.] for _ in range(10)])
```
which then raises no errors for me. I would note that I haven't really thoroughly tested the higher spin stuff so do do plenty of sanity checks!

**Comment by TanTsiChen** [comment]
okay, i will check the high-spin cases.
