### ISSUE TITLE
Clifford simulation?

### ISSUE THREAD

**Issue by yuxuanzhang1995** [jcmgray/quimb#114]
In recent years people have strong interests in random circuit/TN dynamics -- usually they use Clifford gates as a numerical tool due to its high efficiency. I think it'd be really cool to implement that with quimb!

**Comment by ChienKaiMa** [comment]
I think quimb already supports Clifford+T gates for circuits: H, X, Y, Z, S, T, CNOT, CX, CY, CZ.  Maybe you can try it 👍

**Comment by yuxuanzhang1995** [comment]
Thanks for the reply; do you know whether these simulations are implemented in a classical-efficient way (i.e., Clifford representation rather than tensor contraction?)

**Comment by jcmgray** [comment]
Hi @yuxuanzhang1995 - `quimb` is very much a tensor network tool so I don't think it would make sense to implement a separate simulator within it, i.e. the usual stabilizer formalism which there are [already highly optimized libraries for like `stim`](https://github.com/quantumlib/Stim).

1. Having said that, I'm not super familiar with the various clifford methods, if there was a neat way to frame one as a tensor problem that could benefit from contraction optimization etc. I'd be happy to accept an implementation!

2. `quimb` has some quite powerful TN 'simplification' tools - (`full_simplify` and `compress_simplify`) that perform local complexity reducing transformations prior to contraction. In practice these have a huge effect for Clifford gates, though maybe not as powerful as the fully 'symbolic' equivalent ZX-calculus. Very much experimental but in this way there are computational savings that come from the type of gates not just the geometry.

**Comment by yuxuanzhang1995** [comment]
Hi, thanks for the reply! I’m not sure how much this might make sense, but can we do a Clifford class like qiskit did: https://qiskit.org/documentation/stubs/qiskit.quantum_info.Clifford.html <https://qiskit.org/documentation/stubs/qiskit.quantum_info.Clifford.html> 

In case you wonder how this can be useful, https://arxiv.org/abs/2110.02988 <https://arxiv.org/abs/2110.02988> might be a good example! 

Meanwhile, I’ll make sure to try these simplification tools. Thanks a lot!
