### ISSUE TITLE
Git protocol update not reflected in documentation

### ISSUE THREAD

**Issue by SnehalRaj** [jcmgray/quimb#119]
### What happened?

In lieu of the recent changes in git protocol [https://github.blog/2021-09-01-improving-git-protocol-security-github/](link), the old command for installing to the stable version

`pip install --no-deps -U git+git://github.com/jcmgray/quimb.git@develop`

doesn't work anymore.

Following is the updated command

`pip install --no-deps -U git+https://github.com/jcmgray/quimb.git@develop`

### Environment

Yes

**Comment by jcmgray** [comment]
Thanks @SnehalRaj, I'll update the docs momentarily.
