### ISSUE TITLE
Update PyPi package

### ISSUE THREAD

**Issue by nikosavola** [jcmgray/quimb#124]
### What is your issue?

The PyPi package doesn't seem to have been updated since 2020 https://pypi.org/project/quimb/#history. Maybe there should be updates from the development branch more regularly? Some automatic GitHub CI can be setup to do this from just making new version tags.

**Comment by tanlin2013** [comment]
I'm also looking for new release.

Also from the dependency tree, some packages are already expired for quite a while... 
```
quimb 1.3.0 Quantum information and many-body library.
├── cytoolz >=0.8.0
│   └── toolz >=0.8.0 
├── numba >=0.39
│   ├── llvmlite >=0.38.0rc1,<0.39 
│   └── numpy >=1.18,<1.22 
├── numpy >=1.17
├── psutil >=4.3.1
├── scipy >=1.0.0
│   └── numpy >=1.17.3,<1.25.0 
└── tqdm >=4
    └── colorama * 
```

Perhaps it will help to use come CI tools and automatically generate (pre-)releases from the git tags.

**Comment by jcmgray** [comment]
Yes I'll push a new version soon and start doing more regular versions.

Originally the plan was round out some of the new features, bring the tests and docs in line etc, and release a version 2, but I think more incremental updates regardless of making them 'complete' is the way to go in future.

**Comment by tanlin2013** [comment]
Thank you Johnnie! I think that will be indeed better to have a continuous delivery, regardless major or mirror changes. So people know this repo is still alive. Anyway, thank you for the updates. 🚀🚀🚀
