### ISSUE TITLE
Implementation of global symmetry for tensor network

### ISSUE THREAD

**Issue by jerrylvx** [jcmgray/quimb#125]
### Is your feature request related to a problem?

It seems that the current quimb does not possess the capacity for performing TN calculations restricted to certain global charge sectors, which would be particularly beneficial in reducing the memory requirement. The addition of particle number conserving TN structures will be appreciated.

**Comment by jcmgray** [comment]
This is handled by the backend library `symmray` now - https://github.com/jcmgray/symmray.
