### ISSUE TITLE
Unitizing Complex TensorNetworks

### ISSUE THREAD

**Issue by yuxuanzhang1995** [jcmgray/quimb#144]
### What is your issue?

Hi quimb team,

I'm having trouble with the 'TensorNetwork.unitize' while working with complex matrices; it seems to be working fine for the real ones but I'm trying to do some optimizations with complex entrees. Any quick idea on what the issue might be?

Thanks!
Yuxuan

**Comment by jcmgray** [comment]
Hi @yuxuanzhang1995, could you maybe provide minimal example? There are some issues with the stability of autodiff gradients through some of the `unitize` method + backend combinations. Complex matrices potentially sets these off as well.
