### ISSUE TITLE
quimb.tensor.tensor_builder.MPO_ham_ising

### ISSUE THREAD

**Issue by JachyMeow** [jcmgray/quimb#155]
### What happened?

https://github.com/jcmgray/quimb/blob/develop/quimb/tensor/tensor_builder.py#L2763
In this line, “=1/2” should be deleted. Otherwise, the input `S` won't work, so that `MPO_ham_ising` result won't change when `S` changes.

**Comment by jcmgray** [comment]
Thanks for finding this! Should be fixed.
