### ISSUE TITLE
Vectors returned by eigh aren't orthogonal

### ISSUE THREAD

**Issue by paulsbrookes** [jcmgray/quimb#16]
Hello.

Sometimes when I use eigh and I only ask for small number of eigenvectors I find that those eigenvectors aren't orthogonal. For example, let's say that I'm diagonalizing a Hamiltonian produced using ```chain.sim_quimb.ham_gen_quimb``` from my ```chain``` project:

```
n_spins = 8
mu = 0.9
t = 1.0
delta = 0.0
eps = 0.15
ham = ham_gen_quimb(n_spins, mu, t, delta, eps, twist_phase=0.0, step=True)
```
Now I diagonalize ham and ask for 2 eigenvectors. I then check their orthogonality:
```
energies, states = eigh(ham, k=2)
states[:,0].H @ states[:,1]
```
The overlap is unstable but typically it's around 0.01. However if I set k>=33 then the overlap is around 1e-17. 

Is there a way to adjust the accuracy threshold so that eigh returns orthogonal eigenvectors even for smaller values of k?

**Comment by paulsbrookes** [comment]
Actually, I've just realised the two states I'm looking at are degenerate. This is probably the cause of the problem. I've started using Gram-Schmidt orthogonalization on the returned vectors.

**Comment by jcmgray** [comment]
> Actually, I've just realised the two states I'm looking at are degenerate. This is probably the cause of the problem. I've started using Gram-Schmidt orthogonalization on the returned vectors.

Ah OK that might be it!

Here are some other thoughts anyway:
- if you have ``slepc4py`` installed it can often be a better backend than ``scipy`` (maybe you have already?)
- there is a ``tol`` option, but it should be machine precision by default. There is also ``ncv``, which controls how many Lanczos vectors to use, upping this might help (its usually ``max(20, 2*k)``)
- is the hamiltonian definitely hermitian? You might double check results with ``quimb.eig``

**Comment by paulsbrookes** [comment]
> Here are some other thoughts anyway:
> 
> * if you have `slepc4py` installed it can often be a better backend than `scipy` (maybe you have already?)
> * there is a `tol` option, but it should be machine precision by default. There is also `ncv`, which controls how many Lanczos vectors to use, upping this might help (its usually `max(20, 2*k)`)
> * is the hamiltonian definitely hermitian? You might double check results with `quimb.eig`

Thanks Johnnie! I'm installing slepc4py now. How can I control which backend I'm using?

Also, the hamiltonian is definitely hermitian.

**Comment by jcmgray** [comment]
You can just use the ``backend='slepc'`` keyword - there is a bit of explanation [here](https://quimb.readthedocs.io/en/latest/solving%20systems.html#Partial-decomposition).

Note that you will probably need to build ``petsc`` and ``slepc`` yourself if you want complex support - see [here](https://quimb.readthedocs.io/en/latest/installation.html#build-petsc). There are versions on conda-forge etc. but only compiled with support for real data if I recall correctly.

**Comment by paulsbrookes** [comment]
Okay cool. I will try to build ```petsc``` and ```slepc``` tomorrow when I have a bit more time.

Thanks for the info.

**Comment by jcmgray** [comment]
Closing for now @paulsbrookes as not sure what can be fixed but feel free to reopen if you have issues again!
