### ISSUE TITLE
Using quimb within torch on GPU

### ISSUE THREAD

**Issue by yuxuanzhang1995** [jcmgray/quimb#177]
### What is your issue?

Hi quimb team,

In example 12 you showed how to perform optimizations in torch. What do I need to change in order to use cuda as the device for torch optimization?

Best,
Yuxuan

**Comment by jcmgray** [comment]
It should just be as simple as calling:
`apply_to_arrays(lambda x: torch.tensor(x, dtype=torch.float32).cuda())`, or whichever way is your favorite to get the initial torch data onto the gpu:

1. `torch.set_default_device(device)` to set a default permanently
2. `with torch.device(device): ...` to set a default temporarily

**Comment by yuxuanzhang1995** [comment]
That works. Thank you!
