### ISSUE TITLE
Producing an identity Hamiltonian

### ISSUE THREAD

**Issue by emprice** [jcmgray/quimb#20]
I'm trying to learn quimb for a research project and implemented the following simple code. I'm just not seeing what is wrong with doing things this way, but I clearly haven't implemented it correctly yet. This is less of an issue than a question (I haven't seen a discussion forum for this software): What's the difference between a Hamiltonian operator that is the identity matrix at every site, and an actual identity MPO? Why do these act differently on the same state? Perhaps I'm just missing some underlying physics, but this is very non-obvious to me.

```python
import quimb as qu
import quimb.tensor as qtn

k = 4               # number of states
n = 3               # number of sites
cyclic = False      # boundary condition
state = 1           # which state to start in
S = 0.5 * (k - 1)   # system spin in terms of k

# define a "base" state as an outer product of |state> kets
arrays = [qu.basis_vec(state, k)] * n
base = qtn.MPS_product_state(arrays, cyclic=cyclic)

# builder object
ham = qtn.SpinHam(S=S)
ham += 1., 'I'

# build the hamiltonian operator
mpo = ham.build_mpo(n)
mpo.show()

# apply the "identity" hamiltonian to the base state
result = mpo.apply(base)

# what's the outcome?
diff = result - base
print(diff.H @ diff)    # prints 4

mpo = qtn.MPO_identity_like(mpo)

# apply the actual identity operator to the base state
result = mpo.apply(base)

# what's the outcome?
diff = result - base
print(diff.H @ diff)    # prints 0
```

**Comment by jcmgray** [comment]
So what's happening here is that adding the identity term to the ``ham`` is adding a constant offset of 1 *per site*. I.e. (identity 'acting' on site 0) + (identity 'acting' on site 1) + ... which is really just `n` times the identity. 

```python
>>> qu.eigvalsh(mpo.to_dense())
array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

>>> qu.eigvalsh(ham.build_mpo(n).to_dense())
array([3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
       3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
       3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
       3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.])
```
If we normalize by `n` you should get the expected result:
```python
>>> ham = qtn.SpinHam(S=S)
>>> ham += 1 / n, 'I'
>>> qu.norm(ham.build_mpo(n).to_dense() - mpo.to_dense())
0.0
```
The `SpinHam` documentation could maybe be clearer here, but
```python
ham += 1.0, 'I'
```
is really syntactic sugar for
```python
for i in range(n):
    ham += 1.0, 'I', i
```
so it just becomes the 'default' single site term (and also means we don't need to specify ``n``).

**Comment by jcmgray** [comment]
Thinking about it now, possibly the syntax
```python
ham[:] += 1.0, 'I'
```
would be a bit more explicit?

**Comment by emprice** [comment]
Ah, I figured this out at about 1am the night I opened the issue, but it's nice to have confirmation that that is indeed what's happening! I agree that the syntax you propose is more explicit, but I'm not sure it's necessary. I was just misunderstanding what was going on.
