### ISSUE TITLE
Missing dependency on autoray.

### ISSUE THREAD

**Issue by paulsbrookes** [jcmgray/quimb#21]
It looks like autoray is required but it isn't mentioned in the docs (https://quimb.readthedocs.io/en/0.4.0/installation.html) or in setup.py. Would be good to add it as a dependency.

**Comment by jcmgray** [comment]
Thanks for raising this Paul! I've hopefully fixed this in https://github.com/jcmgray/quimb/commit/ec57b6c2b46e10725aafe86724e75e3f74a2424e.

Eventually I'd like to get ``quimb`` and ``autoray`` on conda-forge so that everything can be satisified from one place.
