### ISSUE TITLE
Build MPOs with specific two-site terms

### ISSUE THREAD

**Issue by arturml** [jcmgray/quimb#22]
Hello!

When I try to build an MPO with specific two-site terms, the energy found by DMRG is always zero. For example:

```python
N = 10
builder = SpinHam(1/2)
for i in range(N - 1):
    builder[i, i+1] += 1.0, 'Z', 'Z'

H = builder.build_mpo(N)
dmrg = DMRG2(H)
dmrg.solve(verbosity=1)
```

The variable `builder.var_two_site_terms` is not empty:
```
{(0, 1): [(1.0, 'Z', 'Z')],
 (1, 2): [(1.0, 'Z', 'Z')],
 (2, 3): [(1.0, 'Z', 'Z')],
 (3, 4): [(1.0, 'Z', 'Z')],
 (4, 5): [(1.0, 'Z', 'Z')],
 (5, 6): [(1.0, 'Z', 'Z')],
 (6, 7): [(1.0, 'Z', 'Z')],
 (7, 8): [(1.0, 'Z', 'Z')],
 (8, 9): [(1.0, 'Z', 'Z')]}
```
But the resulting energy is zero. If I use the generic term `builder += 1.0, 'Z', 'Z'`, the resulting energy is -2.25. What I want is to build hamiltonians with site-dependent interaction strength. Am I building MPOs the wrong way?

Thank you!

**Comment by jcmgray** [comment]
Thanks for the report, this certainly look's like a bug! I'll take a closer look shortly.

**Comment by jcmgray** [comment]
This should now be fixed by https://github.com/jcmgray/quimb/commit/36f3b3eac8f09ec25690c05a594b531be0c74ee0. However I might leave this open until you can confirm / don't run into any further bugs!

**Comment by arturml** [comment]
It's working fine now, thank you!

**Comment by arturml** [comment]
Hi, I'm sorry for reviving this issue, but I've found some other problems:

When `N=2`, this error occurs:
```UnboundLocalError: local variable 'i' referenced before assignment```

```python
N = 2
builder = SpinHam(1/2)
for i in range(N - 1):
    builder[i, i+1] += 1.0, 'Z', 'Z'

H = builder.build_mpo(N)
dmrg = DMRG2(H)
dmrg.solve(verbosity=1)
```

If I add a term only to a single pair, this error occurs:
```ValueError: Size of label 'b' for operand 3 (3) does not match previous terms (2).```

```python
N = 10
builder = SpinHam(1/2)
builder[4, 5] += 1.0, 'Z', 'Z'
H = builder.build_mpo(N)
dmrg = DMRG2(H)
dmrg.solve(verbosity=1)
```
I'm sorry for not testing so thoroughly before. Thank you!

**Comment by jcmgray** [comment]
No worries, thanks for finding these now. The first issue should be fixed by https://github.com/jcmgray/quimb/commit/0de0a00141c1958cecf3d20c006d311d563dbf01. 

The second might require a bit more work - essentially the MPO builder expects to find the same number of interaction terms everywhere (and thus build a constant bond MPO).

**Comment by jcmgray** [comment]
https://github.com/jcmgray/quimb/commit/b2874b93b5d24f44f6415e8398b49a3b946b15e9 allows variable bond dimensions/mixed site specific terms so your second example should work now!

**Comment by jcmgray** [comment]
Closing as I think this is fixed, but feel free to reopen if you encouter other related issues @arturml.

**Comment by arturml** [comment]
I haven't had the time to test the changes, but I'll let you know if I encounter something. Thank you! :)
