### ISSUE TITLE
t-DMRG with open boundary condition

### ISSUE THREAD

**Issue by Chapa1** [jcmgray/quimb#23]
Dear creators of quimb,
Could you please answer the questions below.
Is it possible to perform the following calculation using quimb?
I have a one dimensional chain of spinless fermions, periodic boundary conditions.
I need to find the ground state of the hamiltonian at initial time H(0);
solve the Schrodinger equation (SE) with time-dependent hamiltonian H(t) and obtained initial wave function ; calculate the average value of a local operator and the solution of SE.
Does quimb support infinite DMRG or iTEBD calculations?
Thank you in advance.

**Comment by jcmgray** [comment]
Hi @Chapa1:

- There is periodic boundary DMRG yes. 
- There are no spinless fermion hamiltonians constructors yet
- Time dependent TEBD is not implemented but would be quite trivial to add for the evolution
- Local operator expectations yes
- Inifite DMRG/TEBD are not implemented... contributions welcome!
