### ISSUE TITLE
Possible choices for the `optimize` argument in the `local_expectation` function

### ISSUE THREAD

**Issue by PietropaoloFrisoni** [jcmgray/quimb#237]
### What is your issue?

Good evening @jcmgray, I hope you are doing well.

I have a simple question regarding the possible choices/values that the `optimize` function can assume in the computation of the local expectation value of a quantum circuit.

I was unsure if opening this topic as an issue or a question, but it seems to me that the former is more appropriate. I'll try to show why with the following minimal example:

```
import quimb.tensor as qtn
import pennylane as qml

qc = qtn.CircuitMPS(10)

op = qml.PauliX(wires=[0])

qc.local_expectation(op.matrix(), *op.wires, optimize="nosense_value")
```

I provided a nonsense value for the `optimize` argument in this small piece of code, but the code runs with no errors or warnings. 

I could not find a list of possible values that the `optimize` parameter can assume in the documentation. If I missed it, can you please point that out to me? Furthermore, how can I know if the value that I provided is indeed 'used' by the code (see the example above)?

As usual, thank you so much for your time!

All the best.

P.S. If I instantiate an MPS circuit with the option `max_bond=None`, it means I am considering all the Schmidt coefficients in the SVD decomposition, right? I didn't find this explicitly in the documentation, but I think this is the logic. Thank you again!

**Comment by jcmgray** [comment]
Hi @PietropaoloFrisoni,

- `optimize` is always passed down to `tensor_contract` - docs [here](https://quimb.readthedocs.io/en/latest/autoapi/quimb/tensor/tensor_core/index.html#quimb.tensor.tensor_core.tensor_contract).

In this case I presume the TN is simplified to a scalar before any contraction path optimization needs to take place, so the (invalid) argument is never used.

- `max_bond` is always passed down to `tensor_split` - docs [here](https://quimb.readthedocs.io/en/latest/autoapi/quimb/tensor/tensor_core/index.html#quimb.tensor.tensor_core.tensor_split). It limits the maximum number of singular values kept, or there is no limit if it is `None`, but note truncation can still happen via `cutoff`. 

Noted that these things could be more explicitly documented! Indeed there is an 'under construction' page all about TN contraction and the `optimize` kwarg that I just have not had time to complete..

**Comment by PietropaoloFrisoni** [comment]
Thank you @jcmgray, this is very helpful!
