### ISSUE TITLE
ValueError in tests/test_tensor/test_tensor_spectral_approx.py:142

### ISSUE THREAD

**Issue by pulkin** [jcmgray/quimb#24]
Just in case you are not aware: made a fresh install (dev branch) and got this test fail:
```
test_tensor/test_tensor_spectral_approx.py:155: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../quimb/linalg/approx_spectral.py:652: in approx_spectral_function
    samples.append(next(results))
../quimb/linalg/approx_spectral.py:637: in gen_results
    yield single_random_estimate(**kwargs)
../quimb/linalg/approx_spectral.py:453: in single_random_estimate
    Tl, Tv = lanczos_tridiag_eig(alpha, beta, check_finite=False)
../quimb/linalg/approx_spectral.py:297: in lanczos_tridiag_eig
    Tk_banded, lower=True, check_finite=check_finite)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
E               ValueError: array must not contain infs or NaNs
```

Others seem to pass.

**Comment by jcmgray** [comment]
Thanks for the heads up @pulkin. The approx_spectral tests are a bit temperamental, and the ``tensor_spectral_approx`` tests even more so -- I'll try and have a proper look round this soon.

**Comment by jcmgray** [comment]
My thinking on this is that the guilty functionality is fairly niche and probably best archived into its own branch and removed from ``develop``, with the possible exception of the MPO approx_spectral functionality.

**Comment by jcmgray** [comment]
I think the offending test have now been stripped out.
