### ISSUE TITLE
Add "phase" and "cphase" aliases for "u1" and "cu1"

### ISSUE THREAD

**Issue by kevinsung** [jcmgray/quimb#254]
### Is your feature request related to a problem?

The phase gate has the matrix `diag(1, e^{i theta})` (reference: [PhaseGate in Qiskit](https://docs.quantum.ibm.com/api/qiskit/qiskit.circuit.library.PhaseGate)).
The controlled phase gate has the matrix `diag(1, 1, 1, e^{i theta})` (reference: [CPhaseGate in Qiskit](https://docs.quantum.ibm.com/api/qiskit/qiskit.circuit.library.CPhaseGate)).

The phase gate is equivalent to RZ up to global phase, and the controlled phase gate can be implemented with one RZZ and two RZ. Still, these are common gates so it would be nice to have them. If these are welcome,  I can submit a PR.

**Comment by jcmgray** [comment]
Currently implemented is the `u1` and `cu1` gates which I believe are equivalent to these (see e.g. https://github.com/jcmgray/quimb/blob/main/quimb/tensor/circuit.py#L542). Makes sense to me to add `phase` and `cphase` alises however. 

The only minor thing to consider is that where these aliases are currently in place, e.g. `fredkin` -> `cswap` the tensor still gets tagged as `CSWAP` as the 'definitive' version, not sure that is the most useful approach however.

**Comment by kevinsung** [comment]
Ah, I missed those equivalent gates, great! I agree that aliases for `phase` and `cphase` would still be useful.
