### ISSUE TITLE
Setting NUMBA_NUM_THREADS in core.py breaks interaction with other numba based packages

### ISSUE THREAD

**Issue by positr0nium** [jcmgray/quimb#263]
### What is your issue?

In the core.py file, this environment variable is set based on 
``psutil.cpu_count(logical=False)``
I have 16 cpus but 22 logical cores. Quimb therefore sets this variable to 16. Once I initialize my numba based package, this variable is (by numba default) changed to 22, which causes numba to crash. The bug would be fixed by setting ``logical = True``

**Comment by jcmgray** [comment]
I have replaced all numba parallel related functionality now, so this should fixed in the next release.
