### ISSUE TITLE
Error during sampling

### ISSUE THREAD

**Issue by fenephil** [jcmgray/quimb#271]
### What is your issue?

Hello there! First of all I am very grateful for this lovely package, I think it is a state of the art implementation of Tensor Networks.
I am encountering issues however during sampling, I can't comprehend.
So for my thesis I need to build MPS Networks from qiskit circuits/qasm files (using the qiskit_quimb package)
The building of the MPS from gates/circuits works wonderfully. However, often times during sampling (using mps.sample(n)) I get error messages simply by the name of "k1", "b2", etc. Through testing I can assure it is not a problem with qiskit_quimb.
Here is an example:
The following generator function builds a very simple circuit:
```
def gen():
    qubits = list(range(4))
    yield qtn.Gate("U2", params=(0,0), qubits=[0])
    yield qtn.Gate("U2", params=(0,0), qubits=[1])
    yield qtn.Gate("H", params=(), qubits=[2])
    yield qtn.Gate("U2", params=(-np.pi,np.pi), qubits=[3])
    yield qtn.Gate("CX", params=(), qubits=[0, 3])
    yield qtn.Gate("CX", params=(), qubits=[1, 3])
    yield qtn.Gate("CX", params=(), qubits=[2, 3])
    yield qtn.Gate("U2", params=(-np.pi,np.pi), qubits=[0])
    yield qtn.Gate("U2", params=(-np.pi,np.pi), qubits=[1])
    yield qtn.Gate("H", params=(), qubits=[2])
```
Using `MPS = qtn.CircuitMPS.from_gates(
    gates=gen(),
    max_bond=None,
    cutoff=None,
)`
the MPS circuit gets build just fine (inspecting MPS.psi seems everything goes as expected)
However, during sampling, testing for example:
`for s in circ.sample(1):
    print(s)`
it crashes with the following error:

```
KeyError                                  Traceback (most recent call last)
/var/folders/j6/9h7rfh3j123gb05gg7cmq2vc0000gn/T/ipykernel_80359/3528867238.py in ?()
----> 1 for s in circ.sample(1):
      2     print(s)

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/quimb/tensor/circuit.py in ?(self, C, qubits, order, group_size, max_marginal_storage, seed, optimize, backend, dtype, simplify_sequence, simplify_atol, simplify_equalize_norms)
   3153                 #     prob(qubit2='1')=0 given qubit0='0' and qubit1='0'
   3154                 key = (where, tuple(sorted(result.items())))
   3155                 if key not in self._sampled_conditionals:
   3156                     # compute p(qs=x | current bitstring)
-> 3157                     p = self.compute_marginal(
   3158                         where=where,
   3159                         fix=result,
   3160                         optimize=optimize,

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/quimb/tensor/circuit.py in ?(self, where, fix, optimize, backend, dtype, simplify_sequence, simplify_atol, simplify_equalize_norms, rehearse)
   2879 
   2880         # these both are cached and produce TN copies
   2881         if final_marginal:
   2882             # won't need to partially trace anything -> just need ket
-> 2883             nm_lc = self.get_psi_simplified(**fs_opts)
   2884         else:
   2885             # can use lightcone cancellation on partially traced qubits
   2886             nm_lc = self.get_rdm_lightcone_simplified(region, **fs_opts)
...
   9186         """Find the size of ``ind``."""
-> 9187         tid = next(iter(self.ind_map[ind]))
   9188         return self.tensor_map[tid].ind_size(ind)

KeyError: 'k3'
```

I have absolutely no idea, what the reason for this is. Can you guys help me out??

**Comment by jcmgray** [comment]
Hi there @fenephil, it looks like you are on a version of quimb pre v1.8.3, which added a sampling method specific to MPS circuits and should avoid these kind of issues. Maybe try updating and let me know if any problem persists.

**Comment by jcmgray** [comment]
Closing as this should be solved by recent versions, but feel free to re-open if not.
