### ISSUE TITLE
Huge memory use in `als` tensor network fit

### ISSUE THREAD

**Issue by rafaelballester** [jcmgray/quimb#272]
### What is your issue?

I very much appreciate `quimb`'s tensor network fitting methods. However, it looks like the contractions in ALS fitting are far from optimal in the following example:

```import quimb.tensor as qtn
import numpy as np

X = Y = Z = 64
R1 = R2 = R3 = 50

tn_guess = qtn.TensorNetwork([
    qtn.Tensor(np.random.rand(R1, R2, R3), inds=('r1', 'r2', 'r3')),
    qtn.Tensor(np.random.rand(X, R1), inds=('x', 'r1')),
    qtn.Tensor(np.random.rand(Y, R2), inds=('y', 'r2')),
    qtn.Tensor(np.random.rand(Z, R3), inds=('z', 'r3')),
])

tn_target = qtn.Tensor(np.random.rand(X, Y, Z), inds=('x', 'y', 'z'))
tn_fitted = tn_guess.fit(tn_target, method='als', progbar=True, steps=1)
```

gives

`MemoryError: Unable to allocate 116. GiB for an array with shape (50, 50, 50, 50, 50, 50) and data type float64`.

The example is equivalent to a 3D Tucker decomposition. For a $64^3$ tensor, a Tucker ALS algorithm should converge very quickly and certainly not require >100GB memory.

Note: I tried different values of `contract_optimize`, to no avail.

**Comment by jcmgray** [comment]
Yes the ALS currently forms the dense operator to solve the update, which for the core tensor is a matrix of size (50, 50, 50) by (50, 50, 50). Potential upgrades for `quimb` that would be nice in this regard:

- allow als to use an iterative solver with `TNLinearOperator` to allow these relatively large tensors
- have a `tree_fit` function that uses canonicalization to avoid any need for solving at all, for networks such as a tucker with no loops

Note that the 'autodiff' backend should still work fine for this example.

**Comment by jcmgray** [comment]
See (#274) for a new fitting `method='tree'`, that should work well for things like tucker.

**Comment by jcmgray** [comment]
I have also added complex support and an iterative solver to the ALS method there, so that all three `method="als"`, `method="autodiff"` and `method="tree"` should work for this problem now, though the tree method will probably work best.

**Comment by rafaelballester** [comment]
Thanks! This is indeed so much faster.

**Comment by jcmgray** [comment]
Closing with the release of v1.10.0, but do reopen if you find things aren't entirely fixed!
