### ISSUE TITLE
Missing dependency to opt_einsum

### ISSUE THREAD

**Issue by sunqm** [jcmgray/quimb#3]
Without opt_einsum, the code seems to have problems to import the functions in tensor_core.py. Probably it's better to add opt_einsum in setup.py

**Comment by jcmgray** [comment]
Thanks for raising this (for https://github.com/openjournals/joss-reviews/issues/819). Originally the ``quimb.tensor`` package was separate (and optional) but now the core module has begun to depend on it for various reasons. 

Have updated ``setup.py`` and the installation notes, and released a new ``pypi`` version.
