### ISSUE TITLE
slepc error: "The MPI_Comm_rank() function was called before MPI_INIT was invoked"

### ISSUE THREAD

**Issue by paulsbrookes** [jcmgray/quimb#35]
Hi. I have been trying to build `petsc` and `slepc` to use the `slepc` and `slepc-nompi` backends for `eigh`. Both `petsc` and `slepc` pass their tests but when I try to use `slepc-nompi` I receive an error message which I don't understand. Here is the code:

    import quimb as qu
    n = qu.num(10)     
    e, v = qu.eigh(n, k=2, backend='slepc-nompi')

The error message is:

    *** The MPI_Comm_rank() function was called before MPI_INIT was invoked.
    *** This is disallowed by the MPI standard.
    *** Your MPI job will now abort.

Do you know what might be causing this error?

**Comment by jcmgray** [comment]
Hey Paul, mmm not sure! These things are quite hard for me to debug. But just to check, what version of these are you using:

* OS
* compiler
* MPI
* slepc
* petsc

On Ubuntu, with gcc, openmpi 4.0.0 or 1.10.7, and the latest versions of ``slepc`` and ``petsc`` (and ``mpi4py``, ``slepc4py`` and ``petsc4py``) your snippet works fine for me.

**Comment by paulsbrookes** [comment]
Hey Johnie. Here's the info:

- Red Hat 4.8.5-39
- gcc version 4.8.5
- I added `--download-openmpi` when configuring `petsc`, but I don't know which version was downloaded.
- `petsc 3.12`
- `slepc 3.12.1`
- `mpi4py 3.0.3`
- `petsc4py 3.12.0`
- `slepc4py 3.12.0`

I found a couple of other questions (linked below) which mention this kind of error. One possibility is related to having multiple versions of MPI. `petsc` is presumably using the version of OpenMPI it downloaded, but I do have other versions of MPI on my computer, which may be interfering later on. But I don't really understand it.

https://github.com/Argonne-National-Laboratory/DSP/issues/8

https://stackoverflow.com/questions/31687583/mumps-the-mpi-comm-f2c-function-was-called-before-mpi-init-was-invoked

**Comment by jcmgray** [comment]
Ah yes, I suspect multiple MPIs + which mpi4py is pointing at vs which slepc4py is pointing at is the issue. MPI is the one bit of slepc that's probably best installed separately. Some stuff to try:

* Any slepc4py (non quimb) example, same problem?
* Installing mpi4py making sure it points at the same MPI as slepc

If you are using a cluster, use their MPI for sure. Else I generally compile a local version of openmpi v1.10.7 and use that.

**Comment by paulsbrookes** [comment]
Thanks Johnnie! I installed `mpi4py` using `env MPICC=/path/to/mpicc pip install mpi4py` as detailed in https://mpi4py.readthedocs.io/en/stable/install.html and that seems to have fixed the problem.
