### ISSUE TITLE
The iterable function was deprecated in Matplotlib 3.1 and will be removed in 3.3. Use np.iterable instead.

### ISSUE THREAD

**Issue by cyasar** [jcmgray/quimb#37]
/usr/local/lib/python3.6/dist-packages/networkx/drawing/nx_pylab.py:579: MatplotlibDeprecationWarning: 
The iterable function was deprecated in Matplotlib 3.1 and will be removed in 3.3. Use np.iterable instead.
  if not cb.iterable(width):
/usr/local/lib/python3.6/dist-packages/networkx/drawing/nx_pylab.py:585: MatplotlibDeprecationWarning: 
The iterable function was deprecated in Matplotlib 3.1 and will be removed in 3.3. Use np.iterable instead.
  and cb.iterable(edge_color) \
/usr/local/lib/python3.6/dist-packages/networkx/drawing/nx_pylab.py:595: MatplotlibDeprecationWarning: 
The iterable function was deprecated in Matplotlib 3.1 and will be removed in 3.3. Use np.iterable instead.
  for c in edge_color]):

**Comment by jcmgray** [comment]
Hey thanks for the issue, this warning is related purely to ``networkx`` I think - looks like it's [already been fixed](https://github.com/networkx/networkx/pull/3458) so should disappear once a more up-to-date version of ``networkx`` is released/installed.
