### ISSUE TITLE
AttributeError: 'Graph' object has no attribute 'node'

### ISSUE THREAD

**Issue by cyasar** [jcmgray/quimb#38]
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-6-19d8bb4d9316> in <module>
----> 1 circ.psi.graph(color=['PSI0', 'H', 'CNOT', 'RY', 'CZ'])

/usr/local/lib/python3.6/dist-packages/quimb/tensor/tensor_core.py in graph(self, color, show_inds, show_tags, node_size, iterations, k, fix, figsize, legend, return_fig, highlight_inds, initial_layout, edge_alpha, **plot_opts)
   3509 
   3510         for i, t1 in enumerate(ts):
-> 3511             G.node[i]['color'] = None
   3512             for col_tag in colors:
   3513                 if col_tag in t1.tags:

AttributeError: 'Graph' object has no attribute 'node'

**Comment by jcmgray** [comment]
This is from ``networkx`` deprecating the ``.node`` attribute in favour of ``.nodes`` and should already be fixed by https://github.com/jcmgray/quimb/commit/1c1f2531b00e97d8b47cb2b21400497fe6ebfb37 on the develop branch!

**Comment by jcmgray** [comment]
Closing for now, let me know if you can't get it working with a more up-to-date version of ``quimb``.
