### ISSUE TITLE
hamiltonian_builder ignores explicit dtype keyword

### ISSUE THREAD

**Issue by adamcallison** [jcmgray/quimb#45]
The decorator `hamiltonian_builder` in `operators.py` takes in a function which constructs a Hamiltonian and gives back the following:
```python
    @functools.wraps(fn)
    def ham_fn(*args, stype='csr', sparse=False, **kwargs):
        H = fn(*args, **kwargs)

        if isreal(H):
            H = H.real

        if not sparse:
            H = qarray(H.A)
        elif H.format != stype:
            H = H.asformat(stype)

        make_immutable(H)

        return H

    return ham_fn
```
The line `if isreal(H): H = H.real` means that if the caller asked the original function for a complex result via an explicit `dtype` argument, they might get a real result back anyway. Is this intentional? If not, should I make this decorator respect explicit `dtype` inputs?

**Comment by jcmgray** [comment]
Yes, that would be nicer. Check if ``dtype`` has been specified in ``kwargs`` then change the relevant line to something like?
```python
if 'complex' not in str(dtype) and isreal(H):
    ...
```

**Comment by adamcallison** [comment]
Why check explicitly for complex? I was something less heavy-handed like 
```
if not 'dtype' in kwargs and isreal(H):
    H = H.real
```
so that there's just no attempt at dtype coercion if a dtype is explicitly passed.

**Comment by jcmgray** [comment]
Indeed that is simpler!
