### ISSUE TITLE
Recent modifications to tensor_core.py lead to ImportError

### ISSUE THREAD

**Issue by DarthMalloc** [jcmgray/quimb#80]
After installing the latest GitHub, the following error occurs when trying to import quimb:
`/usr/local/lib/python3.7/dist-packages/quimb/__init__.py in <module>()
    173 
    174 # Functions for calculating properties
--> 175 from .calc import (
    176     fidelity,
    177     purify,

/usr/local/lib/python3.7/dist-packages/quimb/calc.py in <module>()
     19     eigh, eigvalsh, norm, sqrtm, norm_trace_dense
     20 )
---> 21 from .linalg.approx_spectral import (
     22     entropy_subsys_approx, tr_sqrt_subsys_approx,
     23     logneg_subsys_approx, gen_bipartite_spectral_fn,

/usr/local/lib/python3.7/dist-packages/quimb/linalg/approx_spectral.py in <module>()
     17 
     18 if find_library('opt_einsum') and find_library('autoray'):
---> 19     from ..tensor.tensor_core import Tensor
     20     from ..tensor.tensor_1d import MatrixProductOperator
     21     from ..tensor.tensor_approx_spectral import construct_lanczos_tridiag_MPO

/usr/local/lib/python3.7/dist-packages/quimb/tensor/__init__.py in <module>()
----> 1 from .tensor_core import (
      2     set_contract_path_cache,
      3     get_contract_strategy,
      4     set_contract_strategy,
      5     contract_strategy,

/usr/local/lib/python3.7/dist-packages/quimb/tensor/tensor_core.py in <module>()
     23 from ..core import (qarray, prod, realify_scalar, vdot, common_type,
     24                     make_immutable)
---> 25 from ..utils import (check_opt, oset, concat, frequencies, unique,
     26                      valmap, ensure_dict, LRU, gen_bipartitions)
     27 from ..gen.rand import randn, seed_rand, rand_matrix, rand_uni

ImportError: cannot import name 'gen_bipartitions' from 'quimb.utils' (/usr/local/lib/python3.7/dist-packages/quimb/utils.py)

`

**Comment by jcmgray** [comment]
Thanks and sorry about that - was a bit hasty commiting, should be fixed now.
