### ISSUE TITLE
Related to reproduce quantum simulation using tensor network

### ISSUE THREAD

**Issue by ZichangHe** [jcmgray/quimb#87]
Hello, I am trying to produce the code in tutorial https://quimb.readthedocs.io/en/latest/tensor-circuit.html

I first define a circuit via `circ = qtn.Circuit(N)`, then when I run the code, it shows the error as
![image](https://user-images.githubusercontent.com/22617423/116654564-407e0800-a93e-11eb-80f9-2882ec76eb44.png)

I am wondering is it some issues related to the installation version? Thanks.

**Comment by jcmgray** [comment]
Hi @ZichangHe, yes I'm afraid that is functionality that has not been released yet - if you install ``quimb`` directly from github you should be able to run the example!

**Comment by ZichangHe** [comment]
Hi @jcmgray, thanks for your reply. I tried `python setup.py build` and  `python setup.py install`. But it has not been successfully installed. Could you please specify how to install it from Github?

**Comment by jcmgray** [comment]
The following should work if you have the other dependencies already installed:
```bash
pip install --no-deps -U git+git://github.com/jcmgray/quimb.git@develop
```
or if you have cloned a local copy and want a 'development' install:
```
cd quimb
pip install --no-deps -U -e .
````
The [installation section of the docs](https://quimb.readthedocs.io/en/latest/installation.html#installation) has a few more details.

**Comment by ZichangHe** [comment]
Thank you a lot, @jcmgray. It works smoothly now.
